### PR TITLE
fix: 230: rollback rollup version to working one

### PR DESCRIPTION
**Pull request by lasmil**
- closes: https://github.com/nearform/github-snooze-chrome-extension/issues/230

### CODE REVIEW

**Review by brunopascottini — APPROVED** [review]

**Comment by ilteoood** [comment]
What if, instead of this, you try to upgrade rollup once again?
Version 3.1.0 is now available, maybe they fixed this.

**Comment by lasmil** [comment]
> What if, instead of this, you try to upgrade rollup once again? Version 3.1.0 is now available, maybe they fixed this.

Tried it, didn't work. :(

**Comment by lasmil** [comment]
@ilteoood , let me know if I can merge this or not :)

**Comment by ilteoood** [comment]
yes, I'll take a look at the upgrade.

**Review by ilteoood — COMMENTED** [review]
LGTM

**Review by ilteoood — APPROVED** [review]

**Comment by lasmil** [comment]
> yes, I'll take a look at the upgrade.

Here is the upgrade issue:
https://github.com/nearform/github-snooze-chrome-extension/issues/232

**Pull request merged**
