### PR TITLE
feat(build): vite migration

### LINKED ISSUE #232: Bump rollup package to version ^3...
Dependabot tried to achieve this in:
https://github.com/nearform/github-snooze-chrome-extension/pull/220
but this caused an issue when trying to log in to the extension using the github PAT.

This issue has been created to bump "rollup" to version 3...

### PR DESCRIPTION
**Pull request by ilteoood**
Closes #232 

Migrate from rollup to vite

### CODE REVIEW

**Comment by simoneb** [comment]
This is not a priority, work which implements things which have been requested first will go in fist please.

**Comment by ilteoood** [comment]
@simoneb 
Initially I though that there could be some conflicts due to file renaming, but at the end only the lock file is conflicting.
It's fine.

**Review by simoneb — CHANGES_REQUESTED** [review]
Apart from being a possibly interesting thought exercise I don't see any benefit in migrating from rollup to vue. Also note this breaks our release workflow.

**Comment by ilteoood** [comment]
The benefits could be less packages to install and less time needed to build everything.
You this breaks the release workflow? I'm creating the same folders (`dist` and `release`), with the same content

**Comment by ilteoood** [comment]
It is useful to reduce the number of packages during install, as we don't have so many rollup plugins as before.
Additionally, it requires less build time as vite is fastest than rollup.

**Review by simoneb — COMMENTED** [review]
there are several eslint warnings being reported

**Review by simoneb — APPROVED** [review]
@brunopascottini can you try this PR out to check it all works fine?

**Comment by brunopascottini** [comment]
@ilteoood I ran some manual tests and it looks good!

**Pull request merged**
